### ISSUE TITLE
[bug]Not same working to xeol-io/xeol 

### ISSUE THREAD

**Issue by sokasanan** [xeol-io/xeol-action#10]
I have built a test with the following Yaml in GithubActions, but it does not detect it well.
xeol-io/xeol has been recently supported, so it works correctly, but the results are different in Actions.

## ScanFromImage

<details>
<summary>yml</summary>

``` 
name: "TestWorkFlow Syft/XEOL"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'ImageRepo'
        required: true
        type: string
      tag:
        description: 'ImageTag'
        required: true
        type: string
      regions:
        description: 'support regions'
        required: true
        type: string
        default: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  TestWorkflow:
    name: "TestWorkFLow Syft Grype XEOL"
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: "ASSUMEROLE ARN FROM Secrets"
        aws-region: ${{ inputs.regions }}
    - name: ECR Login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: ECR IMAGE PULL
      id: imageid
      env:
        ENDPOINT: ${{ inputs.repo }}
        TAGNAME: ${{ inputs.tag }}
      run: |
        echo $ENDPOINT:$TAGNAME
        docker pull $ENDPOINT:$TAGNAME
    - name: Syft
      uses: anchore/sbom-action@v0
      with:
        image: ${{ inputs.repo }}:${{ inputs.tag }}
        format: spdx-json
        artifact-name: sbom.spdx.json
        output-file: "sbom.spdx.json"
    - name: XEOL
      uses: noqcks/xeol-action@v1.0.6
      with:
        image: ${{ inputs.repo }}:${{ inputs.tag }}
        fail-build: false
```

</details>

### Result
```
Run noqcks/xeol-action@v1.0.6
  with:
    image: 34[2] imagename:rel-v.20220715-1358
    fail-build: false
    output-format: table
  env:
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT: sbom.spdx.json
/usr/bin/chmod +x /home/runner/work/_temp/8[3](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:3)580c[4](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:4)7-120a-4bff-a7b3-fae13a936a1d
/home/runner/work/_temp/83[5](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:5)80c47-120a-4bff-a7b3-fae13a93[6](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:6)a1d -b /home/runner/work/_temp/83580c4[7](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:7)-120a-4bff-a7b3-fae13a936a1d_xeol v0.2.0
[info] checking github for release tag='v0.2.0' 
[info] fetching release script for tag='v0.2.0' 
[info] checking github for release tag='v0.2.0' 
[info] using release tag='v0.2.0' version='0.2.0' os='linux' arch='amd64' 
[info] installed /home/runner/work/_temp/[8](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:8)3580c47-120a-4bff-a7b3-fae13a[9](https://github.com/myrepo/actions/runs/6465183770/job/17550930783#step:8:9)36a1d_xeol/xeol 
xeol output...
No eol software found
```

Running a scan from a Syft-generated SBOM produced the same results

## Cause
It appears that you are downloading and using an older (v0.2.0) Xeol. 
Are there any plans to update this action?
If not, I will consider incorporating Xeol myself.

**Comment by noqcks** [comment]
Good catch! Yes, the version is old. https://github.com/xeol-io/xeol-action/blob/main/XeolVersion.js is downloading 0.2.7. 

It looks like our automation for updating the version is failing. I will update the action now

**Comment by noqcks** [comment]
This should now be fixed in xeol-action v1.0.7

**Comment by sokasanan** [comment]
@noqcks 

The scan was performed using 1.0.7.
AlpineLinux was detected, but SpringBoot was not.

```
Run noqcks/xeol-action@v1.0.7
/usr/bin/chmod +x /home/runner/work/_temp/68928dfb-2[19](https://github.com/myrepo/actions/runs/6492768751/job/17632347857#step:8:20)f-466c-901d-2635fadfc498
/home/runner/work/_temp/68928dfb-219f-466c-901d-2635fadfc498 -b /home/runner/work/_temp/68928dfb-219f-466c-901d-2635fadfc498_xeol v0.9.3
[info] checking github for release tag='v0.9.3' 
[info] fetching release script for tag='v0.9.3' 
[info] checking github for release tag='v0.9.3' 
[info] using release tag='v0.9.3' version='0.9.3' os='linux' arch='amd64' 
[info] installed /home/runner/work/_temp/68928dfb-219f-466c-901d-2635fadfc498_xeol/xeol 
xeol output...
  Executing: xeol -o table sbom:sbom.spdx.json
NAME    VERSION  EOL         DAYS EOL  TYPE 
alpine  3.12.3   [20](https://github.com/myrepo/actions/runs/6492768751/job/17632347857#step:8:21)[22](https://github.com/myrepo/actions/runs/6492768751/job/17632347857#step:8:24)-05-01  529       os
```

The image that is being scanned is identical to the one that drafted the XEOL Issue.
We are scanning the SBOM created by Syft, but it was assumed to detect SpringBoot.

https://github.com/xeol-io/xeol/issues/197

**Comment by noqcks** [comment]
Actually, looks like this is actually an issue with old versions of Syft not picking up spring-boot. `anchore/sbom-action@v0.14.3` downloads syft 0.84.0. If you hardpin a newer version with `syft-version` it should work. 

```
      - name: Create SBOM
        uses: anchore/sbom-action@v0.14.3
        with:
          syft-version: v0.93.0
          image: kimb88/hello-world-spring-boot
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
          
      - name: Xeol End-of-Life (EOL) Scan
        uses: xeol-io/xeol-action@v1.0.7
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
```
