### ISSUE TITLE
[Bug] JSON file is not output

### ISSUE THREAD

**Issue by sokasanan** [xeol-io/xeol-action#17]
I implemented GitHubAction in the following form, but it did not output JSON.

```
- name: Run XEOL mw/sw EOL scanner from sbom file and Output file
  uses: noqcks/xeol-action@v1.0.8
  id: xeol
  with:
    sbom: "sbom.spdx.json"
    output-format: json
    fail-build: false

- name: Test Outputs
  run: | 
    echo ${{ steps.xeol.outputs.json }}
```

Outputs are blank
![image](https://github.com/xeol-io/xeol-action/assets/46583021/01bf7d1a-b785-430b-83d5-aedafc58c359)

I think it is because the command is as follows, and in xeol, even the JSON option is standard output.
```
xeol output...
  Executing: xeol -o json sbom:sbom.spdx.json
```

When I ran the same command locally, the JSON file was not created but became stdout , so I assumed it was the same behavior.

**Comment by noqcks** [comment]
👋 I think you might just have the wrong output variable here

It should be `steps.xeol.outputs.report` which will give you "./report.json" in the case that you're using json. Then you can cat the file etc

Let me know if this resolves it!

**Comment by sokasanan** [comment]
```
    - name: Run XEOL mw/sw EOL scanner from sbom file and Output file
      uses: noqcks/xeol-action@v1.0.8
      id: xeol
      with:
        sbom: "sbom.spdx.json"
        output-format: json
        fail-build: false

    - name: Test Outputs
      run: | 
        echo ${{ steps.xeol.outputs.json }}

    - name: Test Outputs
      run: | 
        ls -l
        cat ./results.json
```
To check if there is a file output itself, we changed the above.
With the above, the EOL file was obtained correctly.
The auto-generated file is named "results.json".

![image](https://github.com/xeol-io/xeol-action/assets/46583021/9d3d2221-f609-4a76-99cd-ce05f3f669c3)

However, the outputs values are not working correctly, so we would suggest that you either correct the behavior or provide a correct explanation in the README.
